//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONOS_CUENTA
    {
        public int ID_ABONO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<double> CANT_ABONO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ID_USUARIO { get; set; }
        public string NO_CHEQUE { get; set; }
        public string BANCO { get; set; }
        public Nullable<System.DateTime> FECHA_CHEQUE { get; set; }
        public string EFECTIVO { get; set; }
        public Nullable<int> ID_CUENTA { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<double> DEPOSITO_TOTAL { get; set; }
        public string DEUDA_ACTUAL { get; set; }
        public string CREDITO_DISPO { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public string FOLIO { get; set; }
        public System.DateTime FECHA_ALTA { get; set; }
    }
}
