//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALMACEN1
    {
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ID_DESCUENTO { get; set; }
        public Nullable<double> C_MINIMA { get; set; }
        public Nullable<double> C_MAXIMA { get; set; }
        public string TIPO { get; set; }
        public string VENTA_WEB { get; set; }
        public string MARCA { get; set; }
        public string MATERIAL { get; set; }
        public string COLOR { get; set; }
        public byte[] FOTO_FRENTE { get; set; }
        public byte[] FOTO_LADO { get; set; }
        public Nullable<double> GANANCIA { get; set; }
        public Nullable<double> PRECIO_COSTO { get; set; }
        public Nullable<double> PRECIO_COSTO2 { get; set; }
        public Nullable<double> PRECIO_VENTA { get; set; }
        public int ID { get; set; }
        public string LOCALIZACION { get; set; }
        public string PRECIO_EN { get; set; }
        public Nullable<int> USR_ALTA { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<int> USR_MOD { get; set; }
        public Nullable<System.DateTime> FECHA_MOD { get; set; }
        public string CATEGORIA { get; set; }
        public string ESPECIE { get; set; }
    }
}
