//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ALMACEN3
    {
        public int NUM { get; set; }
        [Required]
        [DisplayName("ID PRODUCTO")]
        [StringLength(25)]
        public string ID_PRODUCTO { get; set; }
        [Required]
        [StringLength(100)]
        public string DESCRIPCION { get; set; }
        [DisplayName("ID DESCUENTO")]
        [StringLength(30)]
        public string ID_DESCUENTO { get; set; }
        [Required]
        [DisplayName("CANTIDAD MINIMA")]
        public double C_MINIMA { get; set; }
        [Required]
        [DisplayName("CANTIDAD MAXIMA")]
        public double C_MAXIMA { get; set; }
        [Required]
        [StringLength(10)]
        public string TIPO { get; set; }
        [Required]
        [DisplayName("VENTA WEB")]
        public string VENTA_WEB { get; set; }
        [Required]
        [StringLength(50)]
        public string MARCA { get; set; }
        [Required]
        [StringLength(20)]
        public string MATERIAL { get; set; }
        [Required]
        [StringLength(10)]
        public string COLOR { get; set; }
        [DisplayName("FOTO FRENTE")]        
        public byte[] FOTO_FRENTE { get; set; }
        [DisplayName("FOTO LADO")]
        public byte[] FOTO_LADO { get; set; }
        [Required]
        public double GANANCIA { get; set; }
        [Required]
        [DisplayName("PRECIO COSTO")]
        public double PRECIO_COSTO { get; set; }
        [Required]
        [StringLength(25)]
        public string CLASIFICACION { get; set; }
        [Required]
        [DisplayName("PRECIO VENTA")]
        public double PRECIO_COSTO2 { get; set; }
        [Required]
        public string LOCALIZACION { get; set; }
        [Required]
        [DisplayName("TIPO DE CAMBIO")]
        [StringLength(10)]
        public string PRECIO_EN { get; set; }
        [Required]
        [DisplayName("USR ALTA")]
        public int USR_ALTA { get; set; }
        [Required]
        [DisplayName("FECHA")]
        [DataType(DataType.DateTime)]
        public DateTime FECHA_ALTA { get; set; }
        public int USR_MOD { get; set; }//DATOS SOLO UTILIZADOS PARA ACTUALIZACION SE ENVIAN EN NULL
        public DateTime FECHA_MOD { get; set; }//DATOS SOLO UTILIZADOS PARA ACTUALIZACION SE ENVIAN EN NULL
        [Required]
        [StringLength(25)]
        public string CATEGORIA { get; set; }
        [Required]
        [StringLength(10)]
        public string PRESENTACION { get; set; }
    }
}
