//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENCIA_TECNICA
    {
        public int ID_AS_TEC { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string MODELO { get; set; }
        public string MARCA { get; set; }
        public string TIPO_ARTICULO { get; set; }
        public string DESCRIPCION_PIEZAS { get; set; }
        public string SUCURSAL { get; set; }
        public string GARANTIA { get; set; }
        public Nullable<System.DateTime> FECHA_DEBE_ATENDER { get; set; }
        public Nullable<System.DateTime> FECHA_ATENDIDO { get; set; }
        public string A_DOMICILIO { get; set; }
        public Nullable<int> ATENDIDO { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_CAPTURA { get; set; }
        public Nullable<double> PRECIO_COTIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_COTIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACEPTADO_PRESUPUESTO { get; set; }
        public string COMENTARIOS_COTIZACION { get; set; }
        public string COMENTARIOS_TECNICOS { get; set; }
    }
}
