//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTVAC
    {
        public decimal ID { get; set; }
        public string ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string USUARIO { get; set; }
        public string COMENTARIO { get; set; }
        public string COMANDA { get; set; }
        public string SUCURSAL { get; set; }
        public string PRODUCCION { get; set; }
        public string COMENTARIO_EXTR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
