//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUES
    {
        public int ID_CHEQUE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TOTAL { get; set; }
        public string TOTAL_LETRA { get; set; }
        public string BANCO { get; set; }
        public string NUM_CHEQUE { get; set; }
        public string TIPO_ORDEN { get; set; }
        public string NUM_ORDEN { get; set; }
        public Nullable<System.DateTime> FECHA_REALIZADO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    }
}
