//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRO_ASISTENCIA_TECNICA
    {
        public int ID { get; set; }
        public Nullable<int> ID_AS_TEC { get; set; }
        public string ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    }
}
