//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRO_MCIA
    {
        public int ID_COBRO { get; set; }
        public string NOMBRE { get; set; }
        public string COMENTARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_INVENTARIO { get; set; }
    }
}
