//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRO_MCIA_DETALLE
    {
        public int ID_COBRO { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public double CANTIDAD { get; set; }
        public double PRECIO_UNITARIO { get; set; }
    }
}
