//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMANDAS_2
    {
        public int ID_COMANDA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_AGENTE { get; set; }
        public Nullable<int> ID_SUCURSAL { get; set; }
        public string NOTAS { get; set; }
        public string ESTADO_ACTUAL { get; set; }
        public string TIPO { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string IMPRE { get; set; }
        public string COMENTARIO { get; set; }
        public string SUCURSAL { get; set; }
    }
}
