//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMANDAS_DETALLES_2
    {
        public int ID_COMANDA { get; set; }
        public int ARTICULO { get; set; }
        public string ID_PRODUCTO { get; set; }
        public double CANTIDAD { get; set; }
        public double CANTIDAD_NO_SIRVIO { get; set; }
        public string TIPO { get; set; }
        public string ESTADO_ACTUAL { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public int I_S { get; set; }
        public string IMPRE { get; set; }
        public string CLASIFICACION { get; set; }
    }
}
