//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORTEPENDIENTE
    {
        public int ID { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public string FACTURA { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string SUCURSAL { get; set; }
        public string ESTADO { get; set; }
    }
}
