//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZA_CLIEN
    {
        public int ID_COTIZA_CLIEN { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_AGENTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
    }
}
