//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZA_REQUI
    {
        public int ID_COTIZACION { get; set; }
        public int ID_REQUISICION { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public double CANTIDAD { get; set; }
        public Nullable<int> DIAS_ENTREGA { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO_ACTUAL { get; set; }
        public Nullable<int> NUMOC { get; set; }
        public string MONEDA { get; set; }
        public Nullable<int> FOLIO { get; set; }
        public Nullable<int> FOLIOREQUI { get; set; }
        public Nullable<int> NO_PEDIDO { get; set; }
    }
}
