//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_VENTA
    {
        public int ID_RELACION { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_CUENTA { get; set; }
        public string ESTADO { get; set; }
    }
}
