//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAS
    {
        public int ID_CUENTA { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> DIAS_CREDITO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCE { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> TOTAL_COMPRA { get; set; }
        public string SUCURSAL { get; set; }
        public string PAGADA { get; set; }
        public string FOLIO { get; set; }
        public Nullable<double> DEUDA { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<double> DEUDA_ACTUAL { get; set; }
    }
}
