//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTOS
    {
        public string ID_DESCUENTO { get; set; }
        public string CLASIFICACION { get; set; }
        public Nullable<double> PORCENTAJE { get; set; }
        public int ID { get; set; }
    }
}
