//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCION
    {
        public decimal ID_DEV { get; set; }
        public string NUM_ORDEN { get; set; }
        public string ID_ENTRADA { get; set; }
        public string ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string PROVEEDOR { get; set; }
        public string MOTIVO { get; set; }
        public string SUCURSAL { get; set; }
        public string FACT_PRO { get; set; }
        public string PRECIO { get; set; }
        public string TOT_DEV { get; set; }
    }
}
