//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DIREIMPOR
    {
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [DisplayName("NOMBRE")]
        public string NOMBRE { get; set; }
        [Required]
        [StringLength(50)]
        [DisplayName("DIRECCIÓN")]
        public string DIRECCION { get; set; }
        [Required]
        [StringLength(50)]
        [DisplayName("CIUDAD")]
        public string CD { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        [Required]
        [DisplayName("ESTATUS")]
        public string STATUS { get; set; }
    }
}
