//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMICILIOS
    {
        public int ID_DOMICILIO { get; set; }
        public string NOM_CLIENTE { get; set; }
        public string DOMICILIO { get; set; }
        public string COLONIA { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DE_HORA { get; set; }
        public string A_HORA { get; set; }
        public string NOTA { get; set; }
        public string NUM_ARTICULOS { get; set; }
        public string ESTADO { get; set; }
        public string ZONA { get; set; }
        public Nullable<int> ID_REPA { get; set; }
        public string COMENTARIOS { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string USUARIO { get; set; }
    }
}
