//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADAS
    {
        public int ID_ENTRADA { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string FACTURA { get; set; }
        public string ID_USUARIO { get; set; }
        public string NUM_ORDEN { get; set; }
        public Nullable<int> ID_ORDEN_COMPRA { get; set; }
    }
}
