//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTPROVEEDOR
    {
        public decimal ID_FP { get; set; }
        public string NOMBRE { get; set; }
        public string NUM_ORDEN_COMPRA { get; set; }
        public string FACTURA_PROV { get; set; }
        public string TIPO { get; set; }
        public string TOTAL { get; set; }
        public string MONEDA { get; set; }
    }
}
