//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCan
    {
        public int ID { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public string FOLIO { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string PASA_FACTU { get; set; }
        public string NOMBRE { get; set; }
    }
}
