//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JR_ALTERNOS
    {
        public int ALTERNO { get; set; }
        public string ID_REPARACION { get; set; }
        public string ID_PRODUCTO1 { get; set; }
        public string ID_PRODUCTO2 { get; set; }
        public double CANTIDAD { get; set; }
    }
}
