//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICITACIONES
    {
        public int ID { get; set; }
        public string ID_PRODUCTO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<double> PRECIO_VENTA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> ID_USUARIO_CAPTURO { get; set; }
        public Nullable<int> CANT_MIN { get; set; }
        public string NO_CONTRATO { get; set; }
        public Nullable<int> CANT_MAX { get; set; }
        public string NO_LICITACION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
    }
}
