//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERMAS
    {
        public int ID_MERMA { get; set; }
        public Nullable<int> ID_NOTA { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CHEKADO { get; set; }
    }
}
