//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JEENContext : DbContext
    {
        public JEENContext()
            : base("name=JEENContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASISTENCIA_TECNICA> ASISTENCIA_TECNICA { get; set; }
        public virtual DbSet<COBRO_MCIA> COBRO_MCIA { get; set; }
        public virtual DbSet<COBRO_MCIA_DETALLE> COBRO_MCIA_DETALLE { get; set; }
        public virtual DbSet<COMANDAS_2> COMANDAS_2 { get; set; }
        public virtual DbSet<COMANDAS_DETALLES_2> COMANDAS_DETALLES_2 { get; set; }
        public virtual DbSet<COTIZA_CLIEN> COTIZA_CLIEN { get; set; }
        public virtual DbSet<COTIZA_REQUI> COTIZA_REQUI { get; set; }
        public virtual DbSet<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public virtual DbSet<DOLAR> DOLAR { get; set; }
        public virtual DbSet<ENTRADAS> ENTRADAS { get; set; }
        public virtual DbSet<EXISTENCIAS> EXISTENCIAS { get; set; }
        public virtual DbSet<EXISTENCIAS_TEMPORAL> EXISTENCIAS_TEMPORAL { get; set; }
        public virtual DbSet<EXISTENCIAS_TEMPORAL_DETALLES> EXISTENCIAS_TEMPORAL_DETALLES { get; set; }
        public virtual DbSet<GARANTIAS> GARANTIAS { get; set; }
        public virtual DbSet<INVENTARIOS> INVENTARIOS { get; set; }
        public virtual DbSet<JR_ALTERNOS> JR_ALTERNOS { get; set; }
        public virtual DbSet<JR_TEMPORALES> JR_TEMPORALES { get; set; }
        public virtual DbSet<MSGAPTONER> MSGAPTONER { get; set; }
        public virtual DbSet<NOTA_CREDITO> NOTA_CREDITO { get; set; }
        public virtual DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual DbSet<ORDEN_RAPIDA> ORDEN_RAPIDA { get; set; }
        public virtual DbSet<PED_CLIEN_DETALLE> PED_CLIEN_DETALLE { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PERDIDAS> PERDIDAS { get; set; }
        public virtual DbSet<PRESTAMOS_CLIENTES> PRESTAMOS_CLIENTES { get; set; }
        public virtual DbSet<PRODUCTOS_CONSUMIBLES> PRODUCTOS_CONSUMIBLES { get; set; }
        public virtual DbSet<PROMOCION> PROMOCION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<PROVEEDOR_ALMACEN1> PROVEEDOR_ALMACEN1 { get; set; }
        public virtual DbSet<PROVEEDOR_CONSUMO> PROVEEDOR_CONSUMO { get; set; }
        public virtual DbSet<REEMP_INV> REEMP_INV { get; set; }
        public virtual DbSet<REQUISICION> REQUISICION { get; set; }
        public virtual DbSet<REV_COMPRA_ALMACEN1> REV_COMPRA_ALMACEN1 { get; set; }
        public virtual DbSet<SUCURSALES> SUCURSALES { get; set; }
        public virtual DbSet<SURTIDOS> SURTIDOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TRASPASOS> TRASPASOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<VENTAS> VENTAS { get; set; }
        public virtual DbSet<ABONOS_CUENTA> ABONOS_CUENTA { get; set; }
        public virtual DbSet<ABONOS_OC_CANCELADOS> ABONOS_OC_CANCELADOS { get; set; }
        public virtual DbSet<ABONOS_PAGO_OC> ABONOS_PAGO_OC { get; set; }
        public virtual DbSet<ALMACEN1> ALMACEN1 { get; set; }
        public virtual DbSet<AutorizaRema> AutorizaRema { get; set; }
        public virtual DbSet<BANCOS> BANCOS { get; set; }
        public virtual DbSet<CAJA_CHICA> CAJA_CHICA { get; set; }
        public virtual DbSet<CANCEPROGRA> CANCEPROGRA { get; set; }
        public virtual DbSet<CARTVAC> CARTVAC { get; set; }
        public virtual DbSet<CHEQUES> CHEQUES { get; set; }
        public virtual DbSet<CLASIFICACIONES> CLASIFICACIONES { get; set; }
        public virtual DbSet<CLATINTONER> CLATINTONER { get; set; }
        public virtual DbSet<COBRANZA> COBRANZA { get; set; }
        public virtual DbSet<COBRO_ASISTENCIA_TECNICA> COBRO_ASISTENCIA_TECNICA { get; set; }
        public virtual DbSet<COLONIAS> COLONIAS { get; set; }
        public virtual DbSet<COMPARATIVO_LICITACIONES> COMPARATIVO_LICITACIONES { get; set; }
        public virtual DbSet<COMPETIDOR_LICITACION> COMPETIDOR_LICITACION { get; set; }
        public virtual DbSet<CORTEPENDIENTE> CORTEPENDIENTE { get; set; }
        public virtual DbSet<COTIZA_CLIEN_DETALLE> COTIZA_CLIEN_DETALLE { get; set; }
        public virtual DbSet<CUENTA_VENTA> CUENTA_VENTA { get; set; }
        public virtual DbSet<CUENTAS> CUENTAS { get; set; }
        public virtual DbSet<DESCUENTOS> DESCUENTOS { get; set; }
        public virtual DbSet<DEV_GARANTIA> DEV_GARANTIA { get; set; }
        public virtual DbSet<DEVOLUCION> DEVOLUCION { get; set; }
        public virtual DbSet<DOMICILIOS> DOMICILIOS { get; set; }
        public virtual DbSet<ENTRADA_PRODUCTO> ENTRADA_PRODUCTO { get; set; }
        public virtual DbSet<ENTRADA_RAPIDAS> ENTRADA_RAPIDAS { get; set; }
        public virtual DbSet<ESTADO_CUENTA> ESTADO_CUENTA { get; set; }
        public virtual DbSet<EXISTENCIA_FIJA> EXISTENCIA_FIJA { get; set; }
        public virtual DbSet<EXISTENCIASTEMPORALES> EXISTENCIASTEMPORALES { get; set; }
        public virtual DbSet<FactCan> FactCan { get; set; }
        public virtual DbSet<FACTPROVEEDOR> FACTPROVEEDOR { get; set; }
        public virtual DbSet<FACTURAS> FACTURAS { get; set; }
        public virtual DbSet<FOLIOSUC> FOLIOSUC { get; set; }
        public virtual DbSet<IMPCOMAN> IMPCOMAN { get; set; }
        public virtual DbSet<INVENTARIO_DETALLE> INVENTARIO_DETALLE { get; set; }
        public virtual DbSet<JUEGO_REPARACION> JUEGO_REPARACION { get; set; }
        public virtual DbSet<LICITACIONES> LICITACIONES { get; set; }
        public virtual DbSet<MERMAS> MERMAS { get; set; }
        public virtual DbSet<MOTIVOS_SCRAP> MOTIVOS_SCRAP { get; set; }
        public virtual DbSet<NOTA_CREDITO_PRODUCTO> NOTA_CREDITO_PRODUCTO { get; set; }
        public virtual DbSet<NOTAS> NOTAS { get; set; }
        public virtual DbSet<ORDEN> ORDEN { get; set; }
        public virtual DbSet<ORDEN_CANCE> ORDEN_CANCE { get; set; }
        public virtual DbSet<ORDEN_COMPRA_DETALLE> ORDEN_COMPRA_DETALLE { get; set; }
        public virtual DbSet<ORDEN_RAPIDA_DETALLE> ORDEN_RAPIDA_DETALLE { get; set; }
        public virtual DbSet<ORDENES_NO_SURTIDAS> ORDENES_NO_SURTIDAS { get; set; }
        public virtual DbSet<PAGO_OC> PAGO_OC { get; set; }
        public virtual DbSet<PASSWORD> PASSWORD { get; set; }
        public virtual DbSet<PED_CLIEN> PED_CLIEN { get; set; }
        public virtual DbSet<PEDIDO_VENTA> PEDIDO_VENTA { get; set; }
        public virtual DbSet<PhotosQuery> PhotosQuery { get; set; }
        public virtual DbSet<PRESTAMOS_CARTUCHOS> PRESTAMOS_CARTUCHOS { get; set; }
        public virtual DbSet<PRESTAMOS_CARTUCHOS_DETALLE> PRESTAMOS_CARTUCHOS_DETALLE { get; set; }
        public virtual DbSet<PRESTAMOS_CLIENTES_DETALLE> PRESTAMOS_CLIENTES_DETALLE { get; set; }
        public virtual DbSet<ProdPend> ProdPend { get; set; }
        public virtual DbSet<PRODUCCION> PRODUCCION { get; set; }
        public virtual DbSet<PRODUCCION_ENTRADAS> PRODUCCION_ENTRADAS { get; set; }
        public virtual DbSet<PRODUCCION_SALIDAS> PRODUCCION_SALIDAS { get; set; }
        public virtual DbSet<PRODUCCIONES_ALMACEN3> PRODUCCIONES_ALMACEN3 { get; set; }
        public virtual DbSet<PROMO_CATEGO> PROMO_CATEGO { get; set; }
        public virtual DbSet<PROMO_PORCE> PROMO_PORCE { get; set; }
        public virtual DbSet<RASTREOREQUI> RASTREOREQUI { get; set; }
        public virtual DbSet<REPAS> REPAS { get; set; }
        public virtual DbSet<REPORTE_COMPRAS_ALM1> REPORTE_COMPRAS_ALM1 { get; set; }
        public virtual DbSet<REQUISICION_ORDEN_RAPIDA> REQUISICION_ORDEN_RAPIDA { get; set; }
        public virtual DbSet<RESPALDOS_BD> RESPALDOS_BD { get; set; }
        public virtual DbSet<SALDO_FAVOR_PROVEEDOR> SALDO_FAVOR_PROVEEDOR { get; set; }
        public virtual DbSet<SALIDAS> SALIDAS { get; set; }
        public virtual DbSet<SalidasInvProd> SalidasInvProd { get; set; }
        public virtual DbSet<SCRAP> SCRAP { get; set; }
        public virtual DbSet<SCRAP_SUCURSAL> SCRAP_SUCURSAL { get; set; }
        public virtual DbSet<SEMANA> SEMANA { get; set; }
        public virtual DbSet<SOLICITUD_NC> SOLICITUD_NC { get; set; }
        public virtual DbSet<TablaPruebaImagen> TablaPruebaImagen { get; set; }
        public virtual DbSet<TPAGOS_OC> TPAGOS_OC { get; set; }
        public virtual DbSet<TRASPASO_DETALLE> TRASPASO_DETALLE { get; set; }
        public virtual DbSet<VALE_CAJA> VALE_CAJA { get; set; }
        public virtual DbSet<Venta_Especial> Venta_Especial { get; set; }
        public virtual DbSet<VENTAS_DETALLE> VENTAS_DETALLE { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<MENSAJERO> MENSAJERO { get; set; }
        public virtual DbSet<PRESENTACION> PRESENTACION { get; set; }
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<ALMACEN3> ALMACEN3 { get; set; }
        public virtual DbSet<ALMACEN2> ALMACEN2 { get; set; }
        public virtual DbSet<ESPECIE> ESPECIE { get; set; }
        public virtual DbSet<DIREIMPOR> DIREIMPOR { get; set; }
    }
}
