//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGAPTONER
    {
        public int ID_MENSAJE { get; set; }
        public string ID_USUARIO_PARA { get; set; }
        public string ID_USUARIO_DE { get; set; }
        public string MENSAJE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public string MINUTOS { get; set; }
    }
}
