//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_CREDITO
    {
        public int ID_NOTA { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MOTIVOCAMBIO { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public string ID_USUARIO { get; set; }
        public string LETRAS { get; set; }
        public string APLICADA { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string FOLIO { get; set; }
    }
}
