//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAS
    {
        public int ID { get; set; }
        public int ID_CLIENTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public string FACTURADA { get; set; }
        public int ID_USER { get; set; }
        public Nullable<int> ID_FACTURA { get; set; }
        public Nullable<int> ID_COMANDA { get; set; }
        public string ORDENCOMPRA { get; set; }
        public string SOLICITO { get; set; }
        public string CREDITO { get; set; }
        public Nullable<int> ID_FORMA_PAGO { get; set; }
        public string BANCO { get; set; }
        public string CHEQUE { get; set; }
    }
}
