//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public int ID_ORDEN { get; set; }
        public string CLIENTE { get; set; }
        public string DIRECCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public string VENDEDOR { get; set; }
        public string FACTURADA { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<int> ID_NOTA { get; set; }
        public double TOTAL { get; set; }
        public string ORDENCOMPRA { get; set; }
        public string SOLICITO { get; set; }
        public string FORMA_PAGO { get; set; }
        public string CONFIRMADA { get; set; }
        public string COMENTARIOS { get; set; }
    }
}
