//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA
    {
        public int ID_ORDEN_COMPRA { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string ENVIARA { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<double> FREIGHT { get; set; }
        public Nullable<double> TAX { get; set; }
        public double OTROS_CARGOS { get; set; }
        public string COMENTARIO { get; set; }
        public string CONFIRMADA { get; set; }
        public string TIPO { get; set; }
        public string TIPO_COMPRA { get; set; }
        public Nullable<int> NUM_ORDEN { get; set; }
        public string MONEDA { get; set; }
        public string FACT_PROVE { get; set; }
        public Nullable<double> TOT_PRO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public int REVISION { get; set; }
        public Nullable<int> ID_USUARIO_AUT { get; set; }
        public string ESTADO { get; set; }
        public string CONTRARECIBO { get; set; }
        public string FORMA_PAGO { get; set; }
        public Nullable<double> DIAS_CREDITO { get; set; }
        public string FACT_PROV { get; set; }
    }
}
