//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_RAPIDA
    {
        public int ID_ORDEN_RAPIDA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public string MONEDA { get; set; }
        public string ESTADO { get; set; }
        public string RENTAS { get; set; }
        public string FAC_NOTA { get; set; }
        public string TOT_PROV { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<double> RETENCION { get; set; }
        public Nullable<double> TOTAL_RETENCION { get; set; }
        public string COMENTARIO_SALID { get; set; }
        public string TIPOIMP { get; set; }
        public string TIP { get; set; }
        public Nullable<int> ID_USUARIO_MOD { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_MOD { get; set; }
    }
}
