//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_OC
    {
        public int ID { get; set; }
        public Nullable<int> ID_ORDEN { get; set; }
        public string TIPOPAGO { get; set; }
        public string BANCO { get; set; }
        public string NUMTRANS { get; set; }
        public string NUMCHEQUE { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
