//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD
    {
        public int ID { get; set; }
        public string DEPT { get; set; }
        public string VENTA { get; set; }
        public string CLAVE { get; set; }
    }
}
