//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PED_CLIEN
    {
        public int NO_PEDIDO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CAPTURA { get; set; }
        public string NO_ORDEN { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURACION { get; set; }
    }
}
