//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_VENTA
    {
        public int ID_Registro { get; set; }
        public Nullable<int> NO_PEDIDO { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
    }
}
