//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public int ID_PEDIDO { get; set; }
        public string SUCURSAL { get; set; }
        public string PIDIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TIPO { get; set; }
        public string COMENTARIO { get; set; }
    }
}
