//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERDIDAS
    {
        public int Id_Perdida { get; set; }
        public string Id_Producto { get; set; }
        public int Id_Inventario { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Cantidad { get; set; }
        public double Precio_Unitario { get; set; }
    }
}
