//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotosQuery
    {
        public int ID_PHOTO { get; set; }
        public byte[] PHOTO { get; set; }
        public string NOTE { get; set; }
        public string ID_CLIENTE { get; set; }
    }
}
