//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PRESENTACION
    {
        public int IdPresentacion { get; set; }
        [Required]
        [StringLength(50)]
        public string Descripcion { get; set; }
        [DisplayName("FECHA REG.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [RegularExpression("(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d", ErrorMessage = "FORMATO INVALIDO (dd-MM-yyyy)")]
        public System.DateTime Fecha { get; set; }
        [Required]
        [Display(Name = "Estatus")]
        public int IdEstatus { get; set; }
    }
}
