//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMOS_CARTUCHOS
    {
        public int ID_PRESTAMO { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string NOTAS { get; set; }
        public string ESTADO { get; set; }
    }
}
