//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCCION
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_USER { get; set; }
        public Nullable<int> ID_USER_CONFIRMAR { get; set; }
        public string EFECTUADO { get; set; }
        public string COMENTARIOS { get; set; }
    }
}
