//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCCION_ENTRADAS
    {
        public string ID_PRODUCTO { get; set; }
        public int CANTIDAD { get; set; }
        public double PRECIO { get; set; }
        public Nullable<int> ID_PRODUCCION { get; set; }
    }
}
