//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS_CONSUMIBLES
    {
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public string NOTAS { get; set; }
        public int ID_PRODUCTO_CONSUMIBLE { get; set; }
    }
}
