//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public int ID_PROMOCION { get; set; }
        public string ID_PRODUCTO { get; set; }
        public double PRECIO_OFERTA { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public string TIPO { get; set; }
        public string ESTADO_ACTUAL { get; set; }
    }
}
