//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR_ALMACEN1
    {
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string MAIL { get; set; }
        public string DIRECCION { get; set; }
        public string IDENTIFICACION { get; set; }
        public string NUMERO_ID { get; set; }
    }
}
