//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REEMP_INV
    {
        public int ID_REEMP { get; set; }
        public string ID_PRODUCTO_DE { get; set; }
        public string ID_PRODUCTO_PARA { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    }
}
