//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPAS
    {
        public int ID_REPA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string CLAVE { get; set; }
    }
}
