//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_COMPRAS_ALM1
    {
        public Nullable<System.DateTime> FECHA_DE { get; set; }
        public Nullable<System.DateTime> FECHA_AL { get; set; }
        public int ID_REPORTE { get; set; }
    }
}
