//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION
    {
        public int ID_REQUISICION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<int> CONTADOR { get; set; }
        public string COTIZADA { get; set; }
        public string ALMACEN { get; set; }
        public string URGENTE { get; set; }
        public Nullable<int> FOLIO { get; set; }
        public string MARCA { get; set; }
        public string COMENTARIO { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> NO_PEDIDO { get; set; }       
    }
}
