//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION_ORDEN_RAPIDA
    {
        public int ID_REQUISICION { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOTAS { get; set; }
        public System.DateTime FECHA_ALTA { get; set; }
        public string ACTIVO { get; set; }
        public string USUARIO { get; set; }
    }
}
