//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REV_COMPRA_ALMACEN1
    {
        public int ID_REVISION { get; set; }
        public string ID_PRODUCTO { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string APROVADO { get; set; }
        public Nullable<System.DateTime> FECHA_APROVADO { get; set; }
        public Nullable<double> CANTIDAD_APROVADA { get; set; }
        public Nullable<double> PRECIO_COMPRA { get; set; }
        public Nullable<int> GRUPO { get; set; }
        public string SUCURSAL { get; set; }
    }
}
