//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_NC
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MOTIVOCAMBIO { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string AUTORIZADO { get; set; }
    }
}
