//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURTIDOS
    {
        public int SURTIDO { get; set; }
        public string SUCURSAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ID_PRODUCTO { get; set; }
        public double CANTIDAD { get; set; }
        public string ESTADO_ACTUAL { get; set; }
    }
}
