//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int Numero { get; set; }
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string PUESTO { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> ID_SUCURSAL { get; set; }
        public string ESTADO { get; set; }
        public string Mail { get; set; }
        public string MailPass { get; set; }
        public string Pe1 { get; set; }
        public string Pe2 { get; set; }
        public string Pe3 { get; set; }
        public string Pe4 { get; set; }
        public string Pe5 { get; set; }
        public string Pe6 { get; set; }
        public string Pe7 { get; set; }
        public string Pe8 { get; set; }
        public string Pe9 { get; set; }
        public string Pe10 { get; set; }
        public string Pe11 { get; set; }
        public string Pe12 { get; set; }
        public string Pe13 { get; set; }
        public string Pe14 { get; set; }
        public string Pe15 { get; set; }
        public string Pe16 { get; set; }
        public string Pe17 { get; set; }
        public string Pe18 { get; set; }
        public string Pe19 { get; set; }
        public string Pe20 { get; set; }
        public string Pe21 { get; set; }
        public string Pe22 { get; set; }
        public string Pe23 { get; set; }
        public string Pe24 { get; set; }
        public string Pe25 { get; set; }
        public string Pe26 { get; set; }
        public string Pe27 { get; set; }
        public string Pe28 { get; set; }
        public string Pe29 { get; set; }
        public string Pe30 { get; set; }
        public string Pe31 { get; set; }
        public string Pe32 { get; set; }
        public string Pe33 { get; set; }
        public string Pe34 { get; set; }
        public string Pe35 { get; set; }
        public string Pe36 { get; set; }
        public string Pe37 { get; set; }
        public string Pe38 { get; set; }
        public string Pe39 { get; set; }
        public string Pe40 { get; set; }
        public string Pe41 { get; set; }
        public string Pe42 { get; set; }
        public string Pe43 { get; set; }
        public string Pe44 { get; set; }
        public string Pe45 { get; set; }
        public string Pe46 { get; set; }
        public string Pe47 { get; set; }
        public string Pe48 { get; set; }
        public string Pe49 { get; set; }
        public string Pe50 { get; set; }
        public string Pe51 { get; set; }
        public string Pe52 { get; set; }
        public string Pe53 { get; set; }
        public string Pe54 { get; set; }
        public string Pe55 { get; set; }
        public string Pe56 { get; set; }
        public string Pe57 { get; set; }
        public string Pe58 { get; set; }
        public string Pe59 { get; set; }
        public string Pe60 { get; set; }
        public string Pe61 { get; set; }
        public string Pe62 { get; set; }
        public string Pe63 { get; set; }
        public string Pe64 { get; set; }
        public string Pe65 { get; set; }
        public string Pe66 { get; set; }
        public string Pe67 { get; set; }
        public string Pe68 { get; set; }
        public string Pe69 { get; set; }
        public string Pe70 { get; set; }
    }
}
