//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALE_CAJA
    {
        public int ID_VALE { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<double> IMPORTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string APLICADO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    }
}
