//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int ID_VENTA { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ID_USUARIO { get; set; }
        public string FACTURADO { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public string TOTAL_LETRA { get; set; }
        public Nullable<System.DateTime> FECHA_HOY { get; set; }
        public string DIA_HOY { get; set; }
        public string MES_HOY { get; set; }
        public string AÑO_HOY { get; set; }
        public Nullable<System.DateTime> FECHA_PAGARE { get; set; }
        public string DIA_PAGARE { get; set; }
        public string MES_PAGARE { get; set; }
        public string AÑO_PAGARE { get; set; }
        public Nullable<decimal> CANTIDAD_PAGARE { get; set; }
        public Nullable<decimal> INTERES { get; set; }
        public string FORMA_PAGO { get; set; }
        public string UNA_EXIBICION { get; set; }
        public string PARCIALIDADES { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> DIAS_CREDITO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCE { get; set; }
        public string TIPO_PAGO { get; set; }
        public string FOLIO { get; set; }
        public string COMENTARIO { get; set; }
        public string NOOC { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public string F_ELECTRO { get; set; }
        public string EFECTO_COMPROBANTE { get; set; }
        public string PEDIMENTO_ADUANA { get; set; }
        public Nullable<System.DateTime> FECHA_PEDIMENTO { get; set; }
        public string NOMBRE_ADUANA { get; set; }
        public string NO_APROBACION { get; set; }
        public Nullable<int> SEC_FACTURA { get; set; }
        public string FLAG_CANCELADO { get; set; }
    }
}
